### PR TITLE
Always set verbosity to 1

### LINKED ISSUE #110: Add warning to the "No files loaded, GHCi is not working properly" error message
Suggest that something might be suppressing module output such as `:set -v0` in the arguments or in their `.ghci` config files. Example module output so they know what `ghci` / `stack ghci` looks like would be good too.

### PR DESCRIPTION
**Pull request by bitemyapp**
Fixes #110 instead of #111 as it is better to just prevent the problem.

### CODE REVIEW

File: src/Language/Haskell/Ghcid.hs [hunk 1]
```diff
@@ -159,7 +159,7 @@ startGhci cmd directory echo0 = do
                 writeIORef stderr []
                 writeInp "import qualified System.IO as INTERNAL_GHCID"
                 writeInp $ ":set prompt " ++ ghcid_prefix
-                writeInp ":set -fno-break-on-exception -fno-break-on-error" -- see #43
+                writeInp ":set -v1 -fno-break-on-exception -fno-break-on-error" -- see #43
```
Comment (ndmitchell) [inline src/Language/Haskell/Ghcid.hs]: Can you adjust the comment to say see #43 and #110, so we can understand the lineage of -v1?

Comment (bitemyapp) [reply src/Language/Haskell/Ghcid.hs]: Absolutely, good idea.

**Comment by ndmitchell** [comment]
Thanks!
